server:
  port: 8015

spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 100MB

  jackson:
    date-format: yyyy-MM-dd hh:mm:ss

  rabbitmq:
    host: 192.168.32.131
    port: 5672
    username: znn
    password: 123456
    virtual-host: /znn

